name: HANNA_environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pandas
  - rdkit
  - transformers
  - tokenizers
  - ipykernel
  - ipywidgets
  - scikit-learn